-- USERS TABLE
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role VARCHAR(20) DEFAULT 'INVESTOR',
  wallet_balance NUMERIC DEFAULT 100000,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);